In [5]:
import pandas as pd
df = pd.read_csv("cars - cars.csv")
df

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

## Question 1 — Check Duplicate Records

In [6]:
import pandas as pd
df = pd.read_csv("cars - cars.csv")
df.duplicated().sum()

np.int64(715)

## Question 2 — Drop Duplicate Records

In [7]:
df_no_duplicates = df.drop_duplicates()
print("Original records:", len(df))
print("Records after dropping duplicates:", len(df_no_duplicates))
df_no_duplicates.head()

Original records: 11914
Records after dropping duplicates: 11199

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

## Question 3 — Check Missing or Null Values

In [8]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

## Question 4 — Drop Missing or Null Values

In [9]:
df_no_missing = df.dropna()
print("Records before dropping missing values:", len(df))
print("Records after dropping missing values:", len(df_no_missing))
df_no_missing.head()

Records before dropping missing values: 11914
Records after dropping missing values: 8084

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

## Question 5 — Top 10 Average MSRP per Car Brand

In [10]:
top_10_brands = (
    df.groupby("Make")["MSRP"]
      .mean()
      .sort_values(ascending=False)
      .head(10)
      .round(0)
)

top_10_brands

Make
Bugatti         1757224.0
Maybach          546222.0
Rolls-Royce      351131.0
Lamborghini      331567.0
Bentley          247169.0
McLaren          239805.0
Ferrari          238219.0
Spyker           213323.0
Aston Martin     197910.0
Maserati         114208.0
Name: MSRP, dtype: float64

## Question 6 — Average MSRP per Year

In [11]:
average_msrp_year = (
    df.groupby("Year")["MSRP"]
      .mean()
      .round(0)
)

average_msrp_year

Year
1990     2020.0
1991     2081.0
1992     2078.0
1993     2187.0
1994     2312.0
1995     2607.0
1996     2497.0
1997     3105.0
1998     2976.0
1999     3096.0
2000     3167.0
2001    41501.0
2002    33744.0
2003    39774.0
2004    36107.0
2005    36747.0
2006    32056.0
2007    34974.0
2008    54139.0
2009    49839.0
2010    50642.0
2011    57548.0
2012    59516.0
2013    48699.0
2014    63226.0
2015    46794.0
2016    47221.0
2017    42192.0
Name: MSRP, dtype: float64

## Question 7 — Average Engine HP and MPG per Year

Average MPG is calculated as:

**(City MPG + Highway MPG) / 2**

In [12]:
df["Average MPG"] = (df["city mpg"] + df["highway MPG"]) / 2

year_summary = (
    df.groupby("Year")
      .agg({
          "Engine HP": "mean",
          "Average MPG": "mean"
      })
      .round(0)
)

year_summary

      Engine HP  Average MPG
Year
1990      141.0         20.0
1991      148.0         19.0
1992      151.0         21.0
1993      156.0         21.0
1994      157.0         21.0
1995      175.0         20.0
1996      174.0         21.0
1997      185.0         19.0
1998      190.0         19.0
1999      189.0         20.0
2000      183.0         21.0
2001      194.0         21.0
2002      196.0         20.0
2003      206.0         20.0
2004      215.0         20.0
2005      219.0         20.0
2006      230.0         20.0
2007      252.0         19.0
2008      256.0         20.0
2009      252.0         21.0
2010      249.0         21.0
2011      263.0         22.0
2012      266.0         23.0
2013      267.0         24.0
2014      292.0         25.0
2015      271.0         25.0
2016      274.0         25.0
2017      275.0         25.0

## Question 8 — Percentage of Compact, Midsize, or Large Cars

In [13]:
size_percentage = (
    df["Vehicle Size"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

size_percentage

Vehicle Size
Compact    39.99
Midsize    36.70
Large      23.31
Name: proportion, dtype: float64

## Question 9 — Most Common Vehicle Styles

In [14]:
vehicle_styles = df["Vehicle Style"].value_counts()
vehicle_styles

Vehicle Style
Sedan                  3048
4dr SUV                2488
Coupe                  1211
Convertible             793
4dr Hatchback           702
Crew Cab Pickup         681
Extended Cab Pickup     623
Wagon                   592
2dr Hatchback           506
Passenger Minivan       417
Regular Cab Pickup      392
2dr SUV                 138
Passenger Van           128
Cargo Van                95
Cargo Minivan            71
Convertible SUV          29
Name: count, dtype: int64

## Question 10 — Brands with Most Vehicles Priced at $40,000+ and Popularity at Least 1000

In [15]:
filtered_cars = df[
    (df["MSRP"] >= 40000) &
    (df["Popularity"] >= 1000)
]
brand_counts = filtered_cars["Make"].value_counts()
brand_counts

Make
Cadillac       354
BMW            276
Audi           224
Chevrolet      216
Ford           145
Toyota         131
Porsche        123
Nissan          91
Ferrari         69
Dodge           58
Lamborghini     52
Chrysler        18
Tesla           18
Kia             17
Honda           14
Hyundai         13
Name: count, dtype: int64